### ISSUE TITLE
Asset files - CSS/fonts/images not loading

### ISSUE THREAD

**Issue by sidthekidder** [PKief/angular-cli-electron#4]
Following [this article](https://medium.com/@PhilippKief/angular-desktop-apps-a9ce9e3574e8) doesn't lead to the files in /assets folder (like css/fonts) getting loaded.

**Comment by PKief** [comment]
@sidthekidder I tried to reproduce your issue but for me everything is working fine.

I added an image into the `src/assets`-folder called "image.jpg".

The image is visible via html like this:

```html
<img src="assets/image.jpg" alt="My Image">
```

It also works properly with css:

```css
.my-image{
  width: 200px;
  height: 300px;
  background-image: url('assets/image.jpg');
  background-size: cover;
}
```

I also tried to import another css file in the `app.component.css` file. The `demo.css` file is located in the same directory:

```css
@import "demo.css";
```

Maybe this [answer](https://stackoverflow.com/a/39152176/6942210) helps you with your assets. Probably it is more a problem that you have with Angular CLI than with electron. Electron is just the wrapper for everything.

I hope that this helps you a little bit.
